#! /bin/bash
set -e

# TODO: make this separate app?
LINEHASH="a7e9f1d3b4c8f2e0"
LINE='[ -f "${HOME}/.profiledir" ] && . "${HOME}/.profiledir"'
LINECMBN="\n${LINE} # ${LINEHASH}"
FILE="${HOME}/.profile"

grep -qF -- "${LINEHASH}" "${FILE}" || echo -e "${LINECMBN}" >> "${FILE}"
cp -f "./.deps.d/profiledir" "${HOME}/.profiledir"
